APP_NAME = "FRP Gui"
APP_VERSION = "1.0.0"
REPO_URL = "https://github.com/Nisbo/frp_gui"
RELEASES_API_URL = "https://api.github.com/repos/Nisbo/frp_gui/releases/latest"
RELEASES_LIST_API_URL = "https://api.github.com/repos/Nisbo/frp_gui/releases?per_page=20"
